spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cdc?serverTimezone=GMT
    username: root
    password: 123456


server:
  port: ${PORT:8012}
mybatis:
  type-aliases-package: com.mywh,qjp.domain
  mapper-locations:
    - mapper/*



